### ISSUE TITLE
Round off error creates a cumulative error that becomes severe even at low recursion depths.

### ISSUE THREAD

**Issue by Northo** [kaprests/Turtle_vector_graphic#1]
Round off error creates a cumulative error that becomes severe even at low recursion depths.

Suggested fix: Store and calculate position in `float`-precision and cast to `int` only when drawing.

**Comment by kaprests** [comment]
Thank you @Northo for bringing up this issue. This was already discovered during testing, and will hopefully be fixed sometime in the future. Also thank you for the suggested fix, seems like a good solution.

**Comment by kaprests** [comment]
This is now fixed with the commit #7716b625a115d71b5b43a94feca6f30d6e662e97

**Comment by Northo** [comment]
Very nice! Marking as closed now.
